### ISSUE TITLE
Bug: Export Presets+Data: Background is not completle saved

### ISSUE THREAD

**Issue by Hexanders** [Julian-Hochhaus/LG4X-V2#12]
Have problems saving the fit results with the: "Export Presets + Data". 
Apparently something goes wrong when creating the results DataFrame. In main.py in ana() pretty much at the end of the function.
Background is incomplete. When I sum the Backgroung and Peaks something is missing. I suspect that only the polynomial background is saved, but Shirley (in this case) is gone.

**Comment by Hexanders** [comment]
[Bi10per.csv](https://github.com/Julian-Hochhaus/LG4X-V2/files/9386599/Bi10per.csv)
[Bi10per_fit.csv](https://github.com/Julian-Hochhaus/LG4X-V2/files/9386600/Bi10per_fit.csv)
[Bi10per_fit.txt](https://github.com/Julian-Hochhaus/LG4X-V2/files/9386601/Bi10per_fit.txt)
[Bi10per_pars.dat.txt](https://github.com/Julian-Hochhaus/LG4X-V2/files/9386602/Bi10per_pars.dat.txt)

This is the data set for Example.

Github dos not support uploading of .dat files so i changed the ending to .txt

**Comment by Julian-Hochhaus** [comment]
Could you please test, if the bug is resolved by 91f4f41

**Comment by Hexanders** [comment]
Yes thanks a lot! Every thing is fine now.
