### ISSUE TITLE
Add functionality for adjusting minima/maxima values of fit parameters.

### ISSUE THREAD

**Issue by Hexanders** [Julian-Hochhaus/LG4X-V2#19]
To achieve better results when fitting or to limit the fit to a certain area.

**Comment by Julian-Hochhaus** [comment]
You can set limits for min and maxima of many parameters if you scroll down in the parameter table below the relative parameters.
However, I am not sure if each parameter's limits work as intended, I haven't tested it extensively.

**Comment by Hexanders** [comment]
Oooo yes, I can see them now. But man is it confusing. We need to find a better solution for this. Like a submenu or drop down menu to break up the cluttered look of the fit parameter table.

**Comment by Julian-Hochhaus** [comment]
Yes indeed, its on my todo list to find a way to declutter the GUI and improve usability. Additionally, I would like to reorganize the code, so that the fitting and the GUI are separated better.

**Comment by Julian-Hochhaus** [comment]
GUI was decluttered and Limits are now accessible in a dedicated submenu since  d675b7ce71ad53820b7b1fc8661f7615f2501a6a
