### ISSUE TITLE
Bug in history_manager

### ISSUE THREAD

**Issue by Julian-Hochhaus** [Julian-Hochhaus/LG4X-V2#21]
Hi, there seems to be a bug in history_manager, I got no time for now to take a look into the topic. Do you have an idea whats wrong here @Hexanders?

` Traceback (most recent call last):
....`
 `
  File "/../main.py", line 1224, in PrettyWidget
    def history_manager(self,pars: list) -> tuple[list, list] or None:
TypeError: 'type' object is not subscriptable
`

**Comment by Hexanders** [comment]
Hi can you post the  whole Traceback?

**Comment by Hexanders** [comment]
Ok
I have an Idia. You use probably Python <3.9. 
There is some stuff going on with Type Hinting in python. After version 3.9 [Tuple[...] has been deprecated in favor of tuple[...]](https://stackoverflow.com/a/67051608/3954117)

**Comment by Julian-Hochhaus** [comment]
Yep, I am still using python 3.8. Bug seems fixed.
