### ISSUE TITLE
Gaussian reference of Voigt profile takes lorenzian as reference value

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#29]
I tried to fit two components, C1: convolution Gaussian/Doniach Doublet and C2: Voigt Profile.
If the gaussian reference of C2 is set to the gaussian value of C1 **not the gaussian value but the lorenzian** value of C1 is used as reference.

[Issue_lorenzian_taken_as_gaussian_reference.txt](https://github.com/Julian-Hochhaus/LG4X-V2/files/10576566/Issue_lorenzian_taken_as_gaussian_reference.txt)

**Comment by Julian-Hochhaus** [comment]
Indeed. Sigma of the gaussian is set to sigma of the doniach-sunjic, which is the lorentzian. Instead, it should be set to the var `gaussian_sigma` of the doniach sunjic which would be the gaussian sigma.
`g2_sigma=gdd1_sigma * g2_gaussian_ratio`
Will fix it asap.
