### ISSUE TITLE
Voigt profile: gaussian and lorenzian have the exact same value

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#30]
When fitting an Voigt profile and all parameters are free, the gaussian and lorenzian value get the exact same value. 
I tries it several times, so it can not be just coincidence. 

[voigt_gaussian_lorenzian_same_value.txt](https://github.com/Julian-Hochhaus/LG4X-V2/files/10576773/voigt_gaussian_lorenzian_same_value.txt)

**Comment by Julian-Hochhaus** [comment]
Yep, names are again mixed up.
Just a remark: Are the amplitudes of your voigts intentionally negative?

**Comment by SHilgers** [comment]
No, negative amplitudes do not make sense, of course. 
For the documentation of the bug I disregarded the other parameters a little bit.

**Comment by Julian-Hochhaus** [comment]
See:

> By default, gamma is constrained to have a value equal to sigma, though it can be varied independently.

[https://lmfit.github.io/lmfit-py/builtin_models.html#voigtmodel](https://lmfit.github.io/lmfit-py/builtin_models.html#voigtmodel)
