### ISSUE TITLE
Error fitting Fermi edge with polynomial background

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#31]
Try to fit a fermi edge with polynomial background throws an error message:

`ERROR:root:Traceback (most recent call last):
  File "main.py", line 1695, in fit
    self.ana("fit")
  File "main.py", line 2834, in ana
    autoscale_y(self.ax)
`

`ValueError: zero-size array to reduction operation maximum which has no identity
`

Is it normal that for a fermi edge no .txt file is saved? Or is there no .txt file output due to the error?

**Comment by Julian-Hochhaus** [comment]
That's not an error with fitting, but with plotting. For some reason, the autoscaling of the plot according to the chosen xlims does not work. I assume that somehow the y-axis object contains no data yet.
What happens if you first press `Evaluate` once? Does this cause the error too? Maybe a quick and dirty fix would then be to call `Evaluate` once before the fitting is started. I need to look at that.

**Comment by SHilgers** [comment]
If I press evaluate the program crashes. So for `Evaluate` there also seem to be problems.

**Comment by SHilgers** [comment]
Not only for the fermi edge, also for other types of spectra and fits `Evaluate` crashes the program. 
Here for example the error message when shirley was choosen as background:

`Traceback (most recent call last):
  File "main.py", line 1690, in eva
    self.ana('eva')
  File "main.py", line 2709, in ana
    self.result2Par(out.params)
  File "main.py", line 2417, in result2Par
    self.bgResult2Pre(out_params)
  File "main.py", line 2347, in bgResult2Pre
    self.pre[1][0][5] = out_params['bg_k'].value
KeyError: 'bg_k'
Abgebrochen (Speicherabzug geschrieben)
`

**Comment by Julian-Hochhaus** [comment]
> Not only for the fermi edge, also for other types of spectra and fits `Evaluate` crashes the program. Here for example the error message when shirley was choosen as background:
> 
> `Traceback (most recent call last): File "main.py", line 1690, in eva self.ana('eva') File "main.py", line 2709, in ana self.result2Par(out.params) File "main.py", line 2417, in result2Par self.bgResult2Pre(out_params) File "main.py", line 2347, in bgResult2Pre self.pre[1][0][5] = out_params['bg_k'].value KeyError: 'bg_k' Abgebrochen (Speicherabzug geschrieben) `

Problem will be fixed by next commit.

However, the original Issue remains unsolved

**Comment by Julian-Hochhaus** [comment]
The bug regarding plotting was already resolved
