### ISSUE TITLE
Crash for Evaluate [Bug]

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#34]
After Evaluate the program crashed with the following errors:

`Max iterations exceeded before convergence.
/home/user/.local/anaconda3/lib/python3.8/site-packages/lmfit/model.py:994: UserWarning: The keyword argument y does not match any arguments of the model function. It will be ignored.
  warnings.warn(f"The keyword argument {name} does not " `

`File "main.py", line 1691, in eva
    self.ana('eva')
  File "main.py", line 2706, in ana
    out = mod.fit(y, pars, x=x, weights=1 / (np.sqrt(y)*np.sqrt(self.rows_lightened)), y=y)`

`ValueError: NaN values detected in your input data or the output of your objective/model function - fitting algorithms cannot handle this! Please read https://lmfit.github.io/lmfit-py/faq.html#i-get-errors-from-nan-in-my-fit-what-can-i-do for more information.
Abgebrochen (Speicherabzug geschrieben)
`

**Comment by SHilgers** [comment]
More error code:
`main.py:2706: RuntimeWarning: divide by zero encountered in divide
  out = mod.fit(y, pars, x=x, weights=1 / (np.sqrt(y)*np.sqrt(self.rows_lightened)), y=y)
/home/steffi/.local/anaconda3/lib/python3.8/site-packages/lmfit/model.py:994: UserWarning: The keyword argument y does not match any arguments of the model function. It will be ignored.
  warnings.warn(f"The keyword argument {name} does not " +
Traceback (most recent call last):
  File "main.py", line 1691, in eva
    self.ana('eva')
  File "main.py", line 2706, in ana
    out = mod.fit(y, pars, x=x, weights=1 / (np.sqrt(y)*np.sqrt(self.rows_lightened)), y=y)
`

`ValueError: NaN values detected in your input data or the output of your objective/model function - fitting algorithms cannot handle this! Please read https://lmfit.github.io/lmfit-py/faq.html#i-get-errors-from-nan-in-my-fit-what-can-i-do for more information.
Abgebrochen (Speicherabzug geschrieben)
`

**Comment by Julian-Hochhaus** [comment]
Right now, the program only crashes if Evaluate is pressed without data being present. As a planned feature, I will introduce a simulation mode

**Comment by Julian-Hochhaus** [comment]
simulation mode was introduced by 5ba89d2996b1a39d64f7d1da674a83c55437c787
