### ISSUE TITLE
Import .csv also opens import VAMAS file

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#35]
For some files, strangely not for all all files, in addition to the .csv import also the VAMAS import window opens. 
Terminal gives the following output:

`strpe = np.loadtxt(str(self.comboBox_file.currentText()), dtype='str', delimiter=',', usecols=1,
main.py:1596: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=1`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using itertools.islice.
``Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use warnings.filterwarnings.  This warning is expected to be removed in the future and is given only once per loadtxt call`.`

**Comment by Julian-Hochhaus** [comment]
as the displayed message is only a warning and the problem being not reproducible, I will close the issue
