### ISSUE TITLE
Empty lorenzian_ref fixes lorenzian (sigma/gamma)

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#41]
If at a Voigt profile the _lorenzian reference_ is left empty, the value _lorenzian (sigma/gamma)_ is not varied, as would be expected, but is fixed. In terminal the lorenzian (sigma/gamma) is also marked as (fixed).

**Comment by Julian-Hochhaus** [comment]
As reported[ here](https://github.com/lmfit/lmfit-py/issues/859), this bug was caused by bugs in the `lmfit` package.
