### ISSUE TITLE
Import  _fit.csv data does not work

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#46]
Importing the saves __fit.csv_ doesn't work. An error window pops up with the message:

_The input .csv is not in the correct format!. The following traceback may help to solve the issue:\n *******************\nValueError: could not convert string to float: 'x' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "main.py", line 1771, in plot self.df = np.loadtxt(str(self.comboBox_file.currentText()), delimiter=',', skiprows=1) File "/home/steffi/.local/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1348, in loadtxt arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter, File "/home/steffi/.local/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in _read arr = _load_from_filelike( ValueError: could not convert string 'x' to float64 at row 0, column 1._

**Comment by Julian-Hochhaus** [comment]
That works as intended. As import files, currently only files with the format `column 1: energy`, `column 2: intensity` are accepted.

However, it makes sense to also allow the reimport of fit results.

**Comment by Julian-Hochhaus** [comment]
added functionality in bc6fea391c4a72830c7e03fda83027d3974c42c9
