### ISSUE TITLE
Frequent crash: RuntimeWarning: divide by zero encountered in divide  

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#55]
Hi,

I frequently encounter crash when fitting and evaluating XPS data.

```
LG4X-V2/Python/main.py:2967: RuntimeWarning: divide by zero encountered in divide
  out = mod.fit(y, pars, x=x, weights=1 / (np.sqrt(raw_y) * np.sqrt(self.rows_lightened)), y=y)
/usr/lib/python3.10/site-packages/lmfit/model.py:994: UserWarning: The keyword argument y does not match any arguments of the model function. It will be ignored.
  warnings.warn(f"The keyword argument {name} does not " +
Traceback (most recent call last):

  File ~/Desktop/software/LG4X-V2/Python/main.py:1867 in eva
    self.ana('eva')

  File ~/Desktop/software/LG4X-V2/Python/main.py:2967 in ana
    out = mod.fit(y, pars, x=x, weights=1 / (np.sqrt(raw_y) * np.sqrt(self.rows_lightened)), y=y)

  File /usr/lib/python3.10/site-packages/lmfit/model.py:1054 in fit
    output.fit(data=data, weights=weights)

  File /usr/lib/python3.10/site-packages/lmfit/model.py:1411 in fit
    _ret = self.minimize(method=self.method)

  File /usr/lib/python3.10/site-packages/lmfit/minimizer.py:2369 in minimize
    return function(**kwargs)

  File /usr/lib/python3.10/site-packages/lmfit/minimizer.py:1693 in leastsq
    lsout = scipy_leastsq(self.__residual, variables, **lskws)

  File /usr/lib64/python3.10/site-packages/scipy/optimize/_minpack_py.py:413 in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)

  File /usr/lib64/python3.10/site-packages/scipy/optimize/_minpack_py.py:26 in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))

  File /usr/lib/python3.10/site-packages/lmfit/minimizer.py:600 in __residual
    return _nan_policy(np.asarray(out).ravel(),

  File /usr/lib/python3.10/site-packages/lmfit/minimizer.py:2453 in _nan_policy
    raise ValueError(msg)

ValueError: NaN values detected in your input data or the output of your objective/model function - fitting algorithms cannot handle this! Please read https://lmfit.github.io/lmfit-py/faq.html#i-get-errors-from-nan-in-my-fit-what-can-i-do for more information.
```
This error is from `ana` function in main.py.
 So I found that there are zero in `raw_y` which come from  `y0`, beyond that I do not know. But from my observation the first value in the `y0` array produce the 0.
 
y0
```
 [0.00000000e+00 5.30753423e+01 7.02504076e+01 3.03932748e+01
 7.35408129e+01 1.16811024e+02 9.91175422e+01 1.00400765e+02
 1.00686216e+02 1.45035025e+02 1.36434581e+02 1.50842381e+02 ...
```

Could it just be that my initial guess is not good enough?
Python 3.10.10
Thank you.

**Comment by Julian-Hochhaus** [comment]
I will need to deep-dive. However, are you sure that your input data does not contain 0 or NaN?

**Comment by kevinsmia1939** [comment]
Yes, I use the same .vms
It is possible that .vms might not be read correctly. I have upload the .vms to #56 .

**Comment by kevinsmia1939** [comment]
Hi,
I manage to crash with the given example data. C1s_sample.csv
Maybe because I was using skew Voigt.

![Screenshot_20230520_030919](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/3293d51d-bc70-4bff-a5fa-9dc577cca4fa)

**Comment by Julian-Hochhaus** [comment]
Regarding your crash with .vms: were you using a static Shirley as background? I wonder how you end up having a 0 as first entry in y0. That's probably causing the error, because then, the first value for weights calculated during fit is Infinity/NaN. [weights~ 1/sqrt(y0)].

But, potentially 0's in y0 may be caused by various reasons and are not necessarily indicating something went wrong. I therefore suggest implementing a check if there are 0's in y0 before calculating weights. If there are 0's, it would make sense to calculate the fit without using weights (will only matter for reduced chi).

If you have time, feel free to tackle that Issue, otherwise, I will look into it soon.

**Comment by kevinsmia1939** [comment]
I always use active Shirley

**Comment by Julian-Hochhaus** [comment]
NaNs and 0's in data are now catched as well as NaN in model function. Should reduce crashes! Hopefully :smiley:

**Comment by kevinsmia1939** [comment]
This fix stop it from completely crashing now. Thanks.
