### ISSUE TITLE
[Enchantment] Amplitude, lorentzian, gaussian, asymmetry, skew limit to 0 as minimum 

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#59]
Hi,
Sometime fitting data yield negative parameter such as negative amplitude, which I believe that does not mean anything. So I think it is better to simply limit these value to be positive value by default.
I am not certain about other parameter like lorentzian, gaussian, asymmetry, frac, skew etc.

What do you think?

**Comment by Julian-Hochhaus** [comment]
in addition, all ratio values (amplitude, lorentzian and so on) should probably be limited to positive values too.

**Comment by kevinsmia1939** [comment]
Thanks for implementing this. I wish I could help more, but I am clueless on Qt at the moment.
