### ISSUE TITLE
Fix exportResults to contain all parameters in .txt

### ISSUE THREAD

**Issue by Julian-Hochhaus** [Julian-Hochhaus/LG4X-V2#60]
Currently, only some parameters are displayed in a table-like export. All parameters should be added to this table.
However, all parameters also are available in export in the lmfit.fit_report section.

**Comment by kevinsmia1939** [comment]
Hi,
Could this also be used to store parameters for the fitting of each region (C1s, O1s, etc.)?? XPS data usually comes with wide spectra and high resolution in specific peaks. So if I were to switch between them, I would want the previous fitting parameters to be there as well.

**Comment by Julian-Hochhaus** [comment]
Something like a fit report for the project? Sounds like a cool idea.
