### ISSUE TITLE
approx.area_p1 could be too much by factor of 10.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#61]
Hi,

I fit the XPS and it gave me the area shown in the screenshot is 118985.3. But when I save the data and calculate the area myself, I got 11898.5

```
file_path = 'UT-O1s.csv'
df = pd.read_csv(file_path, delimiter=',', header=1)
bind = df['corrected x'].to_numpy()
count = df['raw_y'].to_numpy()
bg = df['bg'].to_numpy()
fit = df['sum_fit'].to_numpy()
residual = count - fit
std_res = np.std(residual)
# fit = df.iloc[:, 6].to_numpy()
area1 = -np.trapz(fit, bind)
area2 = -np.trapz(bg, bind)
area_tot = area1-area2
print('area',area_tot)

area 11898.52209162617
```
From very rough area calculation (536-530)*5000 only give 30000.

Could the area reported in the LG4X use different unit, in this case, I use BE ev*intensity(arb unit).

Thanks for clarification.
![Screenshot_20230529_171546](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/59f6cf0b-e6cc-4dea-a3cc-38316fd1fb67)

**Comment by Julian-Hochhaus** [comment]
I am not sure, what is causing that and I will need to check, however, I wonder how this happens, because area is calculated from the result using simpsons rule.

```
y_area = out.eval_components()[strind + str(index_pk + 1) + '_']
area = integrate.simps([y for y, x in zip(y_area, x)])
```
It will probably take some time before I look into it because I will be out of office for two weeks starting from friday :)

**Comment by kevinsmia1939** [comment]
> I am not sure, what is causing that and I will need to check, however, I wonder how this happens, because area is calculated from the result using simpsons rule.
> 
> ```
> y_area = out.eval_components()[strind + str(index_pk + 1) + '_']
> area = integrate.simps([y for y, x in zip(y_area, x)])
> ```
> 
> It will probably take some time before I look into it because I will be out of office for two weeks starting from friday :)

ah, taking vacation, but I'm in a middle of writing thesis but hopefully it will be finish soon.
