### ISSUE TITLE
[Enhancement] Lock zoom on the plot

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#63]
Hi,

Sometimes I zoom in on the plot to see smaller peaks. I tried different parameters to see what was the best fit. But pressing Fit will reset zoom every time I need to zoom in again.

I think it will be a good feature to add.

**Comment by Julian-Hochhaus** [comment]
Sounds nice, I will have to look into this, to do that, we probably need to save the state of all toolbar tools before each fit and afterwards render the new plot in accordance to the old toolbar parameters.

**Comment by kevinsmia1939** [comment]
I found a simple code to print the zoom level (xlim and ylim). Could be helpful.

https://stackoverflow.com/questions/31490436/matplotlib-finding-out-xlim-and-ylim-after-zoom

**Comment by Julian-Hochhaus** [comment]
Saving it for later:
https://stackoverflow.com/questions/50879977/how-to-stop-matplotlibs-navigation-toolbar-zoom-from-reseting-on-plot-update

**Comment by Julian-Hochhaus** [comment]
I tried playing around with it today, however, I was not able to find a satisfying solution.
It seems like xlim and ylim do not hold the zoomed/viewed area. This property is probably saved with the canvas/toolbar. However, [the documentation](https://matplotlib.org/stable/api/backend_bases_api.html#matplotlib.backend_bases.NavigationToolbar2) was not helpful for me so far. Probably, we need to subclass the navigation toolbar, the old zoomed view is somehow accessible, but I don't clearly know how yet :).

Using the left/right arrow buttons in the NavigationToolbar, one is able after plotting to go back in the view stack, which allows to get back the previosly zoomed area. However, I was not able to access these settings correctly.
