### ISSUE TITLE
[Enhancement] Always export unsubtracted background.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#66]
When the curve is fitted, the bg is subtracted. See before and after fittings below.
But when the fitting is done with subtracted bg, the export data also contains subtracted bg. I found this by simply re-plotting peaks in Calc, which only show flat bg.

I think the unsubtracted bg should also be exported.

![Screenshot_20230531_184251](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/e2ed9e70-8234-4ea4-bc1c-5ca27045d4ae)
![Screenshot_20230531_184325](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/e47b1c58-34a7-44e9-9b5b-08253b003e65)

Exported data.
![Screenshot_20230531_184543](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/d5f113be-7529-4fcf-b11f-8f75bf39838f)

**Comment by Julian-Hochhaus** [comment]
You mean that the previously removed background should be exported as well to be able to plot the background (or data with background) afterwards? If yes, then there is probably a bug that needs fixing :)

**Comment by kevinsmia1939** [comment]
Yes, that is correct. Do you have some clue where to look at?

**Comment by Julian-Hochhaus** [comment]
[Here](https://github.com/Julian-Hochhaus/LG4X-V2/blob/f3baa30103f2cf20ffd9711f329dfbb3b67d6e66/Python/main.py#L3206) is the data frame for the export prepared. The bg_mod should contain the precalculated (static) Shirley/Tougaard background.

**Comment by kevinsmia1939** [comment]
I'm trying to understand how it works, because the background become flat when fit or evaluate is click the second time. The first time it does not become flat.

**Comment by Julian-Hochhaus** [comment]
It should become flat the first time. Will have to look if there is some inconsistency

**Comment by Julian-Hochhaus** [comment]
I did some changes to the static background:

1. static background is now always displayed in the plot (and not removed as before)
2. static background is now exported too
