### ISSUE TITLE
Save peak names in preset.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#67]
At the moment, when saving and loading preset, the peak name get reset to C_1, C_2, ...

**Comment by Julian-Hochhaus** [comment]
I am aware of this, in addition, the renamed peak is not renamed in the result tab too. Will fix it after holiday:))

**Comment by Julian-Hochhaus** [comment]
I believe that this enhancement requires a significant amount of code modification to maintain backward compatibility, which is why it will be postponed for now. However, I recognize the need for it and I am willing to introduce this feature in the future.

**Comment by Julian-Hochhaus** [comment]
#3bad8ce8e42bf48432faac2d69dffa91f1db2397 changes the behavior of how headers of the tables are generated. 
The table headers are now available as a parameter and exporting them to the preset should be no longer a hassle. Similar to reloading. 
I will probably introduce this feature soon.
