### ISSUE TITLE
[Enhancement] rem component only remove the last component.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#68]
At the moment, rem component remove last component. rem component should be able to delete other component in between as well.

**Comment by Julian-Hochhaus** [comment]
Yep, and I would like to be able to rearrange components

**Comment by Julian-Hochhaus** [comment]
Introduced by 3bad8ce8e42bf48432faac2d69dffa91f1db2397
