### ISSUE TITLE
Consider adding this to zenodo for new DOI with new name and authors.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#69]
Currently, LG4X can be cite with https://zenodo.org/record/5553131
But now with new name, more authors, and fork, I think it is a good idea to update it.

**Comment by Julian-Hochhaus** [comment]
There is already one. Look at the sidebar or top of Readme :) [https://zenodo.org/record/7937344](https://zenodo.org/record/7937344)

**Comment by kevinsmia1939** [comment]
> There is already one. Look at the sidebar or top of Readme :) https://zenodo.org/record/7937344

Oh I got confuse with the one under citing at the bottom.
