### ISSUE TITLE
Bug Report: Export Preset+Data

### ISSUE THREAD

**Issue by Hexanders** [Julian-Hochhaus/LG4X-V2#7]
When "Export presets+Data" is pressed, the parameters are saved in the ".dat" file: The path for the data is taken as the original path (i.e. in the ".dat" file in the block "[[Data file]]") and not the path where the data has been saved by the "Export presets+Data"

**Comment by Hexanders** [comment]
just found out when loading the file produced by "Export presets+Data" it dos not work at all

**Comment by Julian-Hochhaus** [comment]
By default, the export path is set to the location from where you imported your files, while exporting ( it should not matter if you export data or fitting presets) you normally should have the choice where to save your exported files.
Important note: If exporting via  `Export Presets + Data`, you have two choices, first on where to save the data and fit report, and afterward you should be able to choose where to save the fitting presets (so the .dat file).
The fitting presets are only loadable via `Fitting preset->Load` (`_pars.dat` file). Meanwhile, the `_fit.csv` file containing the fitting results is only loadable via `Importing data`. The third exported file (via `Export Presets+ Data` or `Export`), the `_fit.txt` file contains the fit report and the path of the input data file and is only for the user to have the fit report saved as well. This file can't be loaded in LG4X.

> just found out when loading the file produced by "Export presets+Data" it dos not work at all

It seems like I cannot reproduce this error. Could you please provide additional information?

- Are the parameter files (.dat) exported via `Export Presets + Data` and via `Fitting preset->Save` different in any way? 
- What is the error message you receive while loading?
- If my additional remarks did not yet solved the problem, could you please provide an example file?

**Comment by Hexanders** [comment]
Oops sorry, I was lost. I thought when exporting presets + data it is automatically saved as two files and the opening of the second window, I thought was a bug. Okay now everything works, although I have not managed to load the so saved fit files again. Any attempt to load the bottle file (anything the script would not expect, so try/cacht are not implemented yet) ended in program crash.

So if you save both then it works.


My suggestion would be to pick the parameter classe, because I think it's a bit too much choice and a bit confusing for regular users. 

Thanks for your answer and explanation.

**Comment by Hexanders** [comment]
Ok i look in to the code. There is no parameter class yet. But some parameter_test.py, so it is in progress. So my suggestion is irrelevant at this stage.
