### ISSUE TITLE
Wrong labeling of components after saving and reload

### ISSUE THREAD

**Issue by SHilgers** [Julian-Hochhaus/LG4X-V2#81]
Sometimes after saving and reload the components are labeled wrong, with numbers only, instead of C_2, C_3....
This leads to a crash if you try to fit. 
It's strange that not only the component column has a number, also the column with the checkboxes are numbered.

![image](https://github.com/Julian-Hochhaus/LG4X-V2/assets/32986815/4f024606-c572-47f1-8921-7536d596dd14)
![image](https://github.com/Julian-Hochhaus/LG4X-V2/assets/32986815/ebb40425-b151-4356-be53-46765bf4178b)

**Comment by SHilgers** [comment]
I am not quite sure, but have the impression that it mostly occurs if LG4X was closed and then saved data is loaded.

**Comment by Julian-Hochhaus** [comment]
@SHilgers could you please add the pars.dat file to narrow down the error? I am not sure if it is a problem with saving or loading files.

**Comment by SHilgers** [comment]
Sure, I will do. 
[Test_saving.txt](https://github.com/Julian-Hochhaus/LG4X-V2/files/11981439/Test_saving.txt)
