### ISSUE TITLE
Columns in the component window rescale with every fit. 

### ISSUE THREAD

**Issue by erdzeichen** [Julian-Hochhaus/LG4X-V2#89]
Hej When running a fit the columns int he component window rescale to the default width, that is way to narrow to see anything.

**Comment by Julian-Hochhaus** [comment]
Hey, thanks for the feedback! Which tables do you mean exactly? The one marked in blue (resulting parameters) or the one marked in red (fit parameters)?
![Tables in LG4X-V2](https://github.com/Julian-Hochhaus/LG4X-V2/assets/22680429/b205fd15-d59e-4a22-86a0-ae7b31030f5c)

I have set the column width to a fixed value because otherwise, the table becomes very difficult to comprehend when either the columns are fixed to a large width, or they are scaled according to their content. If you now use more than two components, you have to scroll instead to see all the components used in the fit.

The current value is set to 60, and for my setup, this fits well, as evident from the screenshot attached (tested on different screen sizes and OS). However, one of my colleagues reports similar issues. Maybe it has to do with OS/installed software/screen resolution/system settings or whatever.


Thanks for the feedback! I will think about introducing an option for the user to set the table width individually.

**Comment by Julian-Hochhaus** [comment]
I actually introduced a user config file. It can be found in config/config.ini.

Here, you can set the column width to the value you wish. 
I plan to introduce the option to change the settings not only by editing the ini file, but also using the GUI, but I don't know, if I will introduce such feature before my long weekend holidays :)

**Comment by erdzeichen** [comment]
Hi Julian,
I mean the red zone, but also the blue zone is a bit to large (taking to much space).
I currently use the mouse to drag the columns wider to see what I want, but this resets to the default. Maybe you could simply set the standard width of the columns and zones using a small configuration file? Then users can go in and set those values depending on their screens.  It gets particularly tough when you work mobil on a smaller laptop. 
Anyways, nice work and thanks for your efforts

**Comment by erdzeichen** [comment]
Oi, you were faster in writing, thanks!!

**Comment by Julian-Hochhaus** [comment]
> Hi Julian, I mean the red zone, but also the blue zone is a bit to large (taking to much space). I currently use the mouse to drag the columns wider to see what I want, but this resets to the default. Maybe you could simply set the standard width of the columns and zones using a small configuration file? 

Yep, thanks for the feedback, I already tried several different widths for the different 'zones' of the interface and I am not yet satisfied with the arrangement/widths of the tables. Giving the user full control over these settings makes sense!

**Comment by Julian-Hochhaus** [comment]
GUI option introduced, after my holiday, I will work on introducing more GUI-settings to allow user-customized sizes of 'zones'. 

In addition, I plan to work on setting meaningful float format for all values in all parameter and result tables. Currently, most values get 3 decimal places, this makes sense for most fit parameters, but probably not for the amplitude/height and area values. I plan to set the to maximum of 1 decimal place, maybe even zero. 

But, as now the possibility for the user to customize the interface was introduced using config/config.ini file and the settings tab in the GUI, I might consider adding much more user-customized settings there!

**Comment by Hexanders** [comment]
One of the ways would be to separate the tables and put them in windows. I mean, many people use multiple monitors, so this would be more convenient.

**Comment by Julian-Hochhaus** [comment]
> One of the ways would be to separate the tables and put them in windows. I mean, many people use multiple monitors, so this would be more convenient.

Thanks for the reminder, I once tried to implement an optional two-window mode, but failed. Had a problem with the second window freezing while the fit process was running which led to crashes. 

However, since the fitting process was moved to its own thread, I assume it should no longer be an issue.

Will look into it in the future!

**Comment by Julian-Hochhaus** [comment]
@Hexanders on branch `two_window` I started working on a two-window mode. arrangement/size of widgets is not optimized yet, nevertheless, two-window mode seems to work smoothly so far.

**Comment by Hexanders** [comment]
Could not play with it, have some problems with the configparser.py:

```
$ python3 main.py 
qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.
Traceback (most recent call last):
  File "~/LG4X-V2/Python/main.py", line 4052, in <module>
    w = PrettyWidget()
        ^^^^^^^^^^^^^^
  File "~/LG4X-V2/Python/main.py", line 68, in __init__
    self.two_window_mode = config.getboolean('GUI', 'two_window_mode')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/configparser.py", line 844, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/configparser.py", line 824, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/configparser.py", line 819, in _get
    return conv(self.get(section, option, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'GUI'

```

**Comment by Julian-Hochhaus** [comment]
> Could not play with it, have some problems with the configparser.py:
> 
> ```
> $ python3 main.py 
> qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.
> Traceback (most recent call last):
>   File "~/LG4X-V2/Python/main.py", line 4052, in <module>
>     w = PrettyWidget()
>         ^^^^^^^^^^^^^^
>   File "~/LG4X-V2/Python/main.py", line 68, in __init__
>     self.two_window_mode = config.getboolean('GUI', 'two_window_mode')
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/configparser.py", line 844, in getboolean
>     return self._get_conv(section, option, self._convert_to_boolean,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/configparser.py", line 824, in _get_conv
>     return self._get(section, conv, option, raw=raw, vars=vars,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/configparser.py", line 819, in _get
>     return conv(self.get(section, option, **kwargs))
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/configparser.py", line 797, in get
>     d = self._unify_values(section, vars)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/configparser.py", line 1168, in _unify_values
>     raise NoSectionError(section) from None
> configparser.NoSectionError: No section: 'GUI'
> ```

that means that the configparser was not able to find the config file. Sadly, the error message is not really helpful. configparser does not check if the file is there. In addition, the error message is the same if the path to the config file is longer than 256 characters, which was originally my reason not to set the path to the config file as an absolute path (depending on the directory of the `main.py`-script) but rather setting relative paths, which of course are breaking the program if your execution directory was different to mine.
It is now set to absolute paths and message is printed to the terminal, if the path is too long.

**Comment by Hexanders** [comment]
Nice. That is much better now to work with. 
Thank you for the fix!!!
