### ISSUE TITLE
XPS with binding energy scale, Duniach-Dublett produce upside down peak with negative asymmetry.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#92]
Hi,

I want to use convolution gaussian/Duniach-Dublett  peak shape for Ti 2p  of MXene. I want the peak shape to have a tail similar to what is shown in 10.1016/j.apsusc.2022.153442 in figure 11. So I put asymmetry on it, with the tail going toward high BE, however negative asymmetry cause the issue shown in screenshot below.

I use the latest commit: 0e11a6d3be387c488b5c738bee5af6c9e8a2938b
I have the VMS file if you need them.

Edit: Now I did not get a reverse peak, instead I create everything again instead of loading the saved profile from the latest release.
[MX-UT 0p5 20Ap location U1 in image-0.6530.vms.txt](https://github.com/Julian-Hochhaus/LG4X-V2/files/12726057/MX-UT.0p5.20Ap.location.U1.in.image-0.6530.vms.txt)

![Screenshot_20230926_115012](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/87f3a285-bb6a-4762-9e8f-7e466812950f)
![Screenshot_20230926_115034](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/24e2d6c9-eaaf-4851-8363-91efe94c6179)

I use Python virtualenv for this one.

```
Package         Version
--------------- ------------
asteval         0.9.31
contourpy       1.1.1
cycler          0.11.0
fonttools       4.42.1
future          0.18.3
kiwisolver      1.4.5
lmfit           1.2.2
lmfitxps        1.3.0
matplotlib      3.8.0
numpy           1.26.0
packaging       23.1
pandas          2.1.1
Pillow          10.0.1
pip             23.1.2
pyparsing       3.1.1
PyQt5           5.15.9
PyQt5-Qt5       5.15.2
PyQt5-sip       12.12.2
python-dateutil 2.8.2
pytz            2023.3.post1
scipy           1.11.2
setuptools      67.8.0
six             1.16.0
tzdata          2023.3
uncertainties   3.1.7
wheel           0.40.0
```

**Comment by Julian-Hochhaus** [comment]
Issues that are solved soo smoothly I like the most. :)

Kind regards and good luck with fitting!
