### ISSUE TITLE
Tick box to fixed value for Lorentzian does not fixed the value.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#94]
The tick box to fixed the value during fitting does not fixed the value. The value change when fitting was done.
I use the latest commit: 0e11a6d3be387c488b5c738bee5af6c9e8a2938b

![Screenshot_20230929_185551](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/3ed2b532-e988-4edd-8b64-811ba96c8dff)
![Screenshot_20230929_185629](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/26430fec-afef-4da1-953c-720d0d1a16dd)

**Comment by Julian-Hochhaus** [comment]
I have a idea on how to fix, but can't try out until in like ~10 days when I am back from my trip.

Try substituting in main.py, l2566:

`pars[strind + str(index_pk + 1) + '_gamma'].vary = True`
with;

**Comment by kevinsmia1939** [comment]
> if not self.pre[2][3][2 * index_pk] == 2: pars[strind + str(index_pk + 1) + '_gamma'].vary = True

Work like a charm!

**Comment by Julian-Hochhaus** [comment]
That’s great! Feel free to open pull request!
